module.exports.APP_CONFIG = {
  MONGO_DEV_URI: process.env.MONGO_DEV_URI,
  MONGO_PROD_URI: process.env.MONGO_PROD_URI,
  MONGO_TEST_URI: process.env.MONGO_TEST_URI,
  MONGO_DATABASE_NAME: process.env.MONGO_DATABASE_NAME,
  MONGO_DATABASE_USER: process.env.MONGO_DATABASE_USER,
  MONGO_DATABASE_PASSWORD: process.env.MONGO_DATABASE_PASSWORD,
  APP_NAME: "connect_memo",
  HTTP_PORT: 9797,
}